kind: pipeline
name: ci cd
steps:
  - name: lint
    image: maven:3-jdk-11-slim
    commands:
      - echo "hello, i am here, linting"
  - name: test
    image: maven:3-jdk-11-slim
    commands:
      - mvn clean test
    depends_on:
      - lint
  - name: build
    image: plugins/docker
    settings:
      username:
        from_secret: docker_hub_username
      password:
        from_secret: docker_hub_password
      repo: codefocus/app
      tags:
        - ${DRONE_COMMIT_SHA:-default}
    when:
      branch:
        - main
        - environment/*
  - name: deploy
    image: devth/helm
    environment:
      KUBECONFIG_FILE:
        from_secret: development-kubeconfig
    commands:
      - curl https://google.com -v || true
      - curl https://apiserver.agile-dingo.cns.eu1.cloudmobility.io/version -v --insecure || true
      - curl https://keycloak.eu1.cloudmobility.io -v || true
      - mkdir -p ~/.kube/
      - echo "$KUBECONFIG_FILE" > ~/.kube/config
      - chmod go-r ~/.kube/config
      - helm upgrade --install app ./helm/app --set image.tag=${DRONE_COMMIT_SHA:-default}
    depends_on:
      - build
    when:
      branch:
        - main
        - environment/*
