kind: pipeline
name: test
steps:
  - name: lint
    image: maven:3-jdk-11-slim
    commands:
      - echo "hello, i am here, linting"
  - name: test
    image: maven:3-jdk-11-slim
    commands:
      - mvn clean test
    depends_on:
      - lint

